version: "3.8"
services:
  backend:
    image: "deivisutp/springboot-react-fullstack:26.5.2022.0.49.25"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev