version: "3.8"
services:
  backend:
    image: "deivisutp/springboot-react-fullstack:28.1.2023.23.53.59"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev