version: "3.8"
services:
  backend:
    image: "deivisutp/springboot-react-fullstack:25.5.2022.2.8.47"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev